apiVersion: v1
kind: Service
metadata:
  name: hello-k8s-service
  namespace: hello-ns
spec:
  type: NodePort
  selector:
    app/component: backend-api
  ports:
  - port: 5000 # service port
    targetPort: 5000 # container port
    nodePort: 30000 # node port
